development:
 adapter: mysql
 database: gawkk_development
 username: root
 password: deneme
 host: localhost

test:
 adapter: mysql
 database: gawkk_test
 username: root
 password: deneme
 host: localhost

production:
 adapter: mysql
 database: gawkk_production
 username: root
 password: deneme
 host: localhost

staging:
 adapter: mysql
 database: gawkk_staging_2
 username: root
 password: deneme
 host: localhost
