development:
  adapter: mysql
  database: gawkk_refactor_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: gawkk_test
  username: root
  password:
  host: localhost