development:
 adapter: mysql
 database: gawkk_development
 username: root
 password:
 host: localhost

test:
 adapter: mysql
 database: gawkk_test
 username: root
 password:
 host: localhost

production:
 adapter: mysql
 database: gawkk_production
 username: gawkk_user
 password: 0DU5LjQym7Rrh1P
 host: 75.127.77.202
