development:
 adapter: mysql
 database: gawkk_development
 username: root
 password: root
 host: localhost

test:
 adapter: mysql
 database: gawkk_test
 username: root
 password:
 host: localhost

production:
 adapter: mysql
 database: gawkk_production
 #username: gawkk_user
 #password: 0DU5LjQym7Rrh1P
 username: root
 password: staging 
 host: localhost

staging:
 adapter: mysql
 database: gawkk_staging_2
 username: root
 password: staging
 host: localhost
