development:
 adapter: mysql
 database: gawkk_development
 username: root
 password: root
 host: localhost

test:
 adapter: mysql
 database: gawkk_test
 username: root
 password:
 host: localhost

production:
 adapter: mysql
 database: gawkk_production
 username: debian-sys-maint
 password: Var1U8Scr3F9a4jk 
 host: localhost

staging:
 adapter: mysql
 database: gawkk_staging_2
 username: root
 password: staging
 host: localhost
