development:
    address: localhost
    
production:
    address: 75.127.77.202
    searchd_file_path: /var/www/apps/gawkk/shared/sphinx/
    searchd_log_file: /var/www/apps/gawkk/shared/log/searchd.log
    query_log_file: /var/www/apps/gawkk/shared/log/searchd.query.log
    pid_file: /var/www/apps/gawkk/shared/pids/searchd.production.pid
