development:
    address: localhost
    
production:
    address: 64.120.164.149/
    searchd_file_path: /home/gawkk-app/shared/sphinx/
    searchd_log_file: /home/gawkk-app/shared/log/searchd.log
    query_log_file: /home/gawkk-app/shared/log/searchd.query.log
    pid_file: /home/gawkk-app/shared/pids/searchd.production.pid
